alias ai='ssh -X degoodm@ai.stanford.edu'
alias corn='ssh -X degoodm@corn.stanford.edu'
alias csd='git push && cap staging deploy'
alias ecp='cd ~/Sites/ecp/segmentation-svm'
alias fixtures='rake db:fixtures:load'
alias gp='git commit -am "progress commit" && git push'
alias gbm='git merge --no-ff'
alias mm='cd ~/Sites/metromile'
alias myth='ssh -X degoodm@myth.stanford.edu'
alias ow='cd ~/Sites/consulting/ow/aia'
alias rdbm='rake db:migrate && rake db:test:prepare && rake db:fixtures:load'
alias staging='ssh deploy@www.planestats.com'

: '
DORMANT ALIASES
alias bem='cd /Users/dannygoodman/Desktop/SideIdeas/Consulting/BrandEquityMedia'
alias kaggle='cd ~/Sites/kaggle/online-sales/'
alias mogro='cd ~/Sites/consulting/mogro/mogro'
alias rentlingo='cd ~/Sites/consulting/rentlingo/rentlingo'
alias spl='cd ~/Sites/cs228'
'